Allow for customizing the read and write timeouts
openfaas/golang-http-template pull request #22
Opened 2019-06-12 15:58 UTC by bmcstdio

## Description

Allows for setting the read and write timeouts using the `read_timeout` and `write_timeout` environment variables.
Closes #9.

## How Has This Been Tested?

I've tested this by setting the aforementioned values to `10s` (hence more than the default of `3s`) and executing a piece of code that takes a while to complete:

```
2019/06/12 15:56:23 stderr: 2019/06/12 15:56:23 entered Handle
(...)
2019/06/12 15:56:27 exited Handle
2019/06/12 15:56:27 POST / - 200 OK - ContentLength: 0
```

## How are existing users impacted? What migration steps/scripts do we need?

I am not really sure, since I am fairly new to OpenFAAS.

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [x] read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

2019-06-13 16:00 UTC, ewilde approved these changes
:tada: lgtm

2019-06-13 16:09 UTC, alexellis commented
Hi Bruno

Thanks for your contribution.

We need to be backwards compatible with integer format. 

Please see how this is done in the openfaas-incubator/of-watchdog or openfaas/faas/watchdog and copy the approach.

Regards,

Alex

2019-06-13 16:09 UTC, alexellis requested changes
Changes requested. Please can we also set the timeout to whatever is the default in the of-watchdog?

2019-06-13 16:14 UTC, alexellis commented on template/golang-http-armhf/main.go
> +		panic(err)
I am not keen on the panic, I'd much rather we wrote a `log` message and used the default.

See how the watchdogs handle this please. cc @ewilde

2019-06-13 16:27 UTC, bmcstdio commented
Hi @alexellis,

Thanks for reviewing!

> We need to be backwards compatible with integer format.
> Please see how this is done in the openfaas-incubator/of-watchdog or openfaas/faas/watchdog and copy the approach.

Are you referring to [this function](https://github.com/openfaas-incubator/of-watchdog/blob/master/config/config.go#L118-L127)? If that is the case, I'd like to point out that, IMHO, that function has a few problems: it is neither compatible with integer values (as is being requested), nor is the default value observed properly whenever an environment variable cannot be parsed as a duration. I have put together an example [here](https://play.golang.org/p/lYf5Hq4YbVk).

I will happily amend my commits in order to address your request, but I don't really feel like copying from https://github.com/openfaas-incubator/of-watchdog is the best approach. 🙂 Thoughts?

2019-06-13 16:43 UTC, alexellis commented
Please check both watchdogs. I also mentioned openfaas/faas/watchdog

2019-06-13 16:45 UTC, alexellis commented
> but I don't really feel like copying from X

Why?

2019-06-13 17:05 UTC, closed without merging

2019-06-13 17:11 UTC, alexellis commented
Thanks for your comment. I've updated the code and raised an issue for the discrepancy you found in how of-watchdog parses user-supplied durations. Please feel free to work on the issue linked above. https://github.com/openfaas-incubator/of-watchdog/issues/64

2019-06-17 22:58 UTC, alexellis commented
Hi @bmcstdio, I was under the impression from @ewilde that this was urgently needed. Please let us know if your issue has been addressed and works as expected.

https://github.com/openfaas-incubator/golang-http-template/pull/22#issuecomment-501794638

See comment above for contributing the fix to the other issue you found whilst investigating the solution.

Cheers,

Alex

2019-06-18 07:50 UTC, bmcstdio commented
@alexellis it was indeed urgently needed - fortunately #23 fixed the problem, so thank you very much for that.